/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.vista;

import com.sv.udb.controlador.seresVivosCtrl;
import com.sv.udb.modelo.SeresVivos;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bernardo
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CORTO2 POO1 :: LUIS ENRIQUE ARAUJO AQUINO");
        this.actTab();
    }
    
    private void limp()
    {
        this.txtcodi_sere.setText("");
        this.txtDesc_sere.setText("");
        this.txtNomb_sere.setText("");
        this.llenCmb();
    }
    
    
    private void actTab() {
        try {
            seresVivosCtrl obje = new seresVivosCtrl();
            DefaultTableModel model = (DefaultTableModel)this.tblSersVivs.getModel();
            while(model.getRowCount()>0){model.removeRow(0);} //Limpiar modelo
            //Se agregan todos los que esten en la lista
            for (SeresVivos temp : obje.consTodo())
            {
                model.addRow(new Object[]{temp, temp.getDesc_sere(), temp.getPadre_sere()});
            }
            limp();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void llenCmb() {
        try {
            seresVivosCtrl obje = new seresVivosCtrl();
            this.cmbSersVivs.removeAllItems();
            DefaultComboBoxModel<SeresVivos> dcm = new DefaultComboBoxModel<>();
            SeresVivos nulo = new SeresVivos();
            nulo.setNomb_sere("-Seleccione uno si desea-");
            dcm.addElement(nulo);
            for (SeresVivos temp : obje.consTodo())
                {
                    dcm.addElement(temp);
                }
            this.cmbSersVivs.setModel((ComboBoxModel)dcm);
        } catch (Exception e) {
            e.printStackTrace();
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodi_sere = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomb_sere = new javax.swing.JTextField();
        txtDesc_sere = new javax.swing.JTextField();
        btnNuev = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        btnCons = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        cmbSersVivs = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSersVivs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Formulario"));

        btnGuar.setBackground(new java.awt.Color(102, 153, 255));
        btnGuar.setText("Guardar");
        btnGuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        txtcodi_sere.setEditable(false);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        btnNuev.setBackground(new java.awt.Color(0, 204, 153));
        btnNuev.setText("Nuevo");
        btnNuev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevActionPerformed(evt);
            }
        });

        btnModi.setBackground(new java.awt.Color(51, 204, 0));
        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });

        btnCons.setBackground(new java.awt.Color(204, 204, 0));
        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });

        btnElim.setBackground(new java.awt.Color(255, 102, 102));
        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });

        cmbSersVivs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Pertenece a:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(31, 31, 31)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodi_sere, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomb_sere, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnElim)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnNuev, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCons)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSersVivs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDesc_sere))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodi_sere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomb_sere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDesc_sere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSersVivs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuar)
                    .addComponent(btnNuev)
                    .addComponent(btnCons))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModi)
                    .addComponent(btnElim))
                .addGap(26, 26, 26))
        );

        tblSersVivs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Pertenece a"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSersVivs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSersVivsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSersVivs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarActionPerformed
        try {
            if (!this.txtNomb_sere.getText().isEmpty() && !this.txtDesc_sere.getText().isEmpty())
            {
                SeresVivos obje = new SeresVivos();
                //obje.setCodiEqui(Integer.parseInt(txtCodi.getText()));
                obje.setNomb_sere(this.txtNomb_sere.getText());
                obje.setDesc_sere(this.txtDesc_sere.getText());
                SeresVivos refe = (SeresVivos)this.cmbSersVivs.getSelectedItem();
                obje.setCodi_refe_sere(refe.getCodi_sere());
                if (this.cmbSersVivs.getSelectedIndex() == 0)
                {
                    if (new seresVivosCtrl().guar2(obje))
                    {
                        JOptionPane.showMessageDialog(this, "Datos guardados");
                        this.actTab();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
                else
                {
                    if (new seresVivosCtrl().guar(obje))
                    {
                        JOptionPane.showMessageDialog(this, "Datos guardados");
                        this.actTab();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Por favor complete los campos requeridos (Nombre y descripción) el 'pertenece a' si desea que sea nulo seleccione el primero ");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Hubo un problema al guardar los datos");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuarActionPerformed

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        this.actTab();
    }//GEN-LAST:event_btnConsActionPerformed

    private void tblSersVivsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSersVivsMouseClicked
        try {
            int fila = this.tblSersVivs.getSelectedRow();
            if (fila >= 0) {
                SeresVivos obje = (SeresVivos)this.tblSersVivs.getValueAt(fila, 0);
                this.txtcodi_sere.setText(String.valueOf(obje.getCodi_sere()));
                this.txtNomb_sere.setText(obje.getNomb_sere());
                this.cmbSersVivs.setEditable(true); 
                this.cmbSersVivs.setSelectedItem((SeresVivos)new seresVivosCtrl().consUno(obje.getCodi_refe_sere()));
                this.cmbSersVivs.setEditable(false);
                this.txtDesc_sere.setText(obje.getDesc_sere());
            }
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblSersVivsMouseClicked

    private void btnNuevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevActionPerformed
        this.limp();
    }//GEN-LAST:event_btnNuevActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
        if (this.tblSersVivs.getSelectedRow() > -1)
        {
            try {
                if (!this.txtcodi_sere.getText().isEmpty()) {
                    SeresVivos obje = new SeresVivos();
                    obje.setCodi_sere(Integer.parseInt(this.txtcodi_sere.getText()));
                    if (JOptionPane.showConfirmDialog(this, "Esta seguro de que desea eliminar este registro?", "AVISO", JOptionPane.YES_NO_OPTION) == 0) 
                    {
                        if (new seresVivosCtrl().dele(obje))
                        {
                            JOptionPane.showMessageDialog(this, "Datos Eliminados");
                            this.actTab();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Error, no se pudo eliminar el registro");
                        }
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Por favor Seleccione un registro (el campo codigo debe estar lleno)");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un registro a Eliminar");
        }
    }//GEN-LAST:event_btnElimActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed
        try {
            if (!this.txtNomb_sere.getText().isEmpty() && !this.txtDesc_sere.getText().isEmpty() && !this.txtcodi_sere.getText().isEmpty())
            {
                SeresVivos obje = new SeresVivos();
                obje.setCodi_sere(Integer.parseInt(this.txtcodi_sere.getText()));
                obje.setNomb_sere(this.txtNomb_sere.getText());
                obje.setDesc_sere(this.txtDesc_sere.getText());
                SeresVivos refe = (SeresVivos)this.cmbSersVivs.getSelectedItem();
                obje.setCodi_refe_sere(refe.getCodi_sere());
                if (this.cmbSersVivs.getSelectedIndex() == 0)
                {
                    if (new seresVivosCtrl().upda2(obje))
                    {
                        JOptionPane.showMessageDialog(this, "Datos guardados");
                        this.actTab();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
                else
                {
                    if (new seresVivosCtrl().upda(obje))
                    {
                        JOptionPane.showMessageDialog(this, "Datos guardados");
                        this.actTab();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Por favor complete los campos requeridos (Nombre y descripción) y seleccione un registro");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Hubo un problema al guardar los datos");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnModiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnGuar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnNuev;
    private javax.swing.JComboBox<String> cmbSersVivs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSersVivs;
    private javax.swing.JTextField txtDesc_sere;
    private javax.swing.JTextField txtNomb_sere;
    private javax.swing.JTextField txtcodi_sere;
    // End of variables declaration//GEN-END:variables
}
